name 'jlyheden-nss'
version '0.0.1'
author 'Johan Lyheden'
license 'Apache License 2.0'
project_page 'https://bitbucket.org/jlyheden/puppet-nss'
source 'git@bitbucket.org:jlyheden/puppet-nss.git'
summary 'Manages NSS'
description 'A Puppet module for managing NSS'
dependency 'puppetlabs/stdlib', '>=3.2.0'
