name 'artisol-nss'
version '0.0.1'

author 'Johan Lyheden'
license ''
project_page 'https://bitbucket.org/jlyheden/puppet-nss'
source 'git@bitbucket.org:jlyheden/puppet-nss.git'
summary 'A Puppet module for managing NSS'
description ''
dependency 'puppetlabs/stdlib', '==3.2.0'
