name 'jlyheden-nss'
version '0.0.1'
author 'Johan Lyheden'
license 'Apache License 2.0'
project_page 'https://github.com/jlyheden/puppet-nss'
source ''
summary 'Manages NSS'
description 'A Puppet module for managing NSS'
dependency 'puppetlabs/stdlib', '>=3.2.0'
